apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: secret-ops
spec:
  containers:
  - image: nginx
    name: nginx
    envFrom:
      - secretRef:
          name: ext-service-secret
  restartPolicy: Never