apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: secret-ops
spec:
  containers:
    - image: nginx
      name: consumer
      volumeMounts:
        - name: secret-volume
          mountPath: /var/app
          readOnly: true
  volumes:
    - name: secret-volume
      secret:
        secretName: key-secret
