apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    name: nginx-pod
spec:
  containers:
  - name: nginx-pod
    image: nginx:1.17.10
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  # initContainers:
  #   - name: busybox
  #     image: busybox
  #     command: ['sh', '-c', 'wget -q -O- nginx-pod:80 && sleep 3600']
