apiVersion: v1
kind: Pod
metadata:
  name: consumer
  namespace: nextapp
spec:
  containers:
  - name: consumer
    image: "nginx:latest"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - name: config-volume
        mountPath: /etc/config/config.json
  volumes:
    - name: config-volume
      configMap:
        name: app-config
  restartPolicy: Never
